### PR TITLE
[release-4.10] Bug 2079318: Remove PSP gatherer (#608)

### PR DESCRIPTION
**Pull request by tremes**
This is removing PSP gatherer

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- Removing [psp_names.json](https://github.com/openshift/insights-operator/compare/release-4.10...tremes:remove-psp-4.10?expand=1#diff-0b1122243cfb0e72b38b86d60fea83f8282e08042c7242d46d566471942f5551)

## Documentation

- Removed from the [gathered-data.md](https://github.com/openshift/insights-operator/compare/release-4.10...tremes:remove-psp-4.10?expand=1#diff-af75e5b22f25c37be5653ee0c3ac041d589e78c78e5c5c7b651c923055bf55b5)

## Unit Tests

- Removing [pod_security_policies_test.go](https://github.com/openshift/insights-operator/compare/release-4.10...tremes:remove-psp-4.10?expand=1#diff-26c1c5c2660e72dd783db7d120dc8b91a8123c8dd8b90696ff524ceeaf6ab0d6)

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=2079318
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
very simple one.
/lgtm

**Review by natiiix — APPROVED** [review]
I have not tested this, but it is clear from the code changes that if the CI jobs pass, then IO isn't broken.
/lgtm

**Comment by tremes** [comment]
Our tests must be updated to pass
/hold

**Pull request merged**
