### PR TITLE
gather route metrics

### PR DESCRIPTION
**Pull request by tjungblu**
This PR implements a new data enhancement to gather data about OpenShift Routes (sub part of [NE-682](https://issues.redhat.com/browse/NE-682)). 

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

where can I add that?

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- `pkg/gatherers/clusterconfig/openshift_routes_test.go`

## Privacy

There are no sensitive data in the newly collected information. Host and TLS information were wiped before collecting.

## Changelog

No

## Breaking Changes

No

## References

https://issues.redhat.com/browse/NE-682

### CODE REVIEW

**Comment by tjungblu** [comment]
b

**Comment by tremes** [comment]
Hi @tjungblu. Thanks for the PR. What is the reason of this data pls? Do we need the complete `route` definitions? I am just little bit affraid it will be quite a lot of new data. Do we have any estimate on how many `routes` to expect?

**Comment by tjungblu** [comment]
@tremes good question, background is in here: https://issues.redhat.com/browse/NE-682

I think it might be enough to just collect the count of the routes in the cluster. Can I send the counter as a record as well or does it expect some k8s resource?

**Comment by tremes** [comment]
@tjungblu you can basically send whatever you want (but json please) :-) so yeah counter is OK. I was thinking about e.g namespace name and count of routes (or maybe just a list of route names...), but AFAIK namespace name is considered as sensitive data. Up to you then.... :-)

**Comment by tjungblu** [comment]
@tremes haha fair enough. I don't even think we would need the names or the namespaces. 

What's the preferred way of doing such a counter?

```
records = append(records, record.Record{
	Name: fmt.Sprintf("config/routes/%s/%s", item.GetNamespace(), item.GetName()),
	Item: "{ \"count\": 1}"
})
```

for each route? or just one record with the full count?

```
records = append(records, record.Record{
	Name: "config/routes",
	Item: "{ \"count\": 42 }"
})
```

**Comment by tjungblu** [comment]
closing here, since we already have that metric through the cluster usage resources in prometheus. @tremes thanks for you help though, great discussion!

**Pull request closed without merging**
