### PR TITLE
[release-4.3] Bug 1836815: Gather image registry config

### PR DESCRIPTION
**Pull request by martinkunc**
Picks #103 and updates dependencies

### CODE REVIEW

**Comment by martinkunc** [comment]
Release managers: The change list is huge, but this is neccessary to bring in the refactoring which happened in 4.5 and 4.4 + take all the missing commits from 4.5 together

**Review by natiiix — APPROVED** [review]
/lgtm
*Obligatory "I didn't go through the changes line by line"*

**Comment by martinkunc** [comment]
@markmc Apologise for direct ping, but could you please grant cherry-pick-approved to this PR ? It is collection of changes after refactoring including Adding collection to image registry in the insights operator. We had similar big CLs coming to 4.4 and 4.5 and by merging this, we could easily merge changes coming from latest versions, which includes this refactoring. We still have changes required to be merged to 4.3 unfortunately.
Thank you!

**Pull request merged**
