### PR TITLE
Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout

### PR DESCRIPTION
**Pull request by p0lyn0mial**
This repository uses the delegated authentication which has been identified to contain a bug that increases the number of watch requests against the Kube API server.

We provided a temporary branch that contains a fix and switched this repository to that branch. 

With this change, `k8s.io/apiserver` points to `temporary-watch-reduction-patch-1.21` to pick up `k/k/pull/101102` 

Feel free to remove it once the upstream PR merges and a new Z release is cut.
## Categories

- [X] Bugfix
- [] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `path/to/sample_data.json`

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
@p0lyn0mial Can you please link the URL to the `k/k/pull/101102` ?

**Comment by tremes** [comment]
OK this one https://github.com/kubernetes/kubernetes/pull/101102 right.

**Comment by p0lyn0mial** [comment]
> OK this one kubernetes/kubernetes#101102 right. 

correct

> I guess we will need to wait for k8s.io/apiserver v0.22.0 to be able to remove the temporary fix right.

no, for `1.21.1`

**Comment by tremes** [comment]
Ohh these versions...OK :) Thanks. 
/lgtm

**Pull request merged**
