### PR TITLE
[release-4.8] Bug 2014634: obfuscation ovn clusters bug

### PR DESCRIPTION
**Pull request by Serhii1011010**
Backport of https://github.com/openshift/insights-operator/pull/515

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

No changes

## Documentation

No changes

## Unit Tests

No changes

## Privacy

No new data was collected

## Changelog

No

## Breaking Changes

No

## References

https://issues.redhat.com/browse/CCXDEV-6141
https://bugzilla.redhat.com/show_bug.cgi?id=
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
At first I was little bit confused by the bigger changes compared to the  4.9 backport. Veriffied and it seems working fine. Thanks.
/lgtm

**Comment by hardys** [comment]
[patch-manager] Approving cherry-pick with a score of 0.20

**Pull request merged**
