### PR TITLE
[release-4.5] Bug 1904079: Add hostsubnet to sample archive & fix bug…

### PR DESCRIPTION
**Pull request by tremes**
… in the hostsubnet gathering

This is bugfixing for hostsubnet gathering

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json`
- `docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json`
- and more ....

## Documentation

- no need to update

## Unit Tests

- no update

## Privacy

IP addresses in the hostsubnet definition already anonymized

## References

https://bugzilla.redhat.com/show_bug.cgi?id=1904079

### CODE REVIEW

**Comment by markmc** [comment]
(patch manager) removing cherry-pick-approved for this round

**Review by rluders — APPROVED** [review]
/lgtm

**Pull request merged**
