### PR TITLE
Bug 1820633: Cherry-pick release 4.4 Support for specific http proxy for the service

### PR DESCRIPTION
**Pull request by martinkunc**
Cherry-pick support for specific http proxy
Obviously I wasn't successful with squashing the commits here, so I had to cherry pick them manually this time.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
It seems to me that there's more code than it supposed to be, is this correct?

If you try to apply the [patch](https://patch-diff.githubusercontent.com/raw/openshift/insights-operator/pull/87.patch) directly does it work?

Also, the title of this PR is misleading, we are backporting proxy to 4.4.

**Comment by martinkunc** [comment]
@jwforres Could I ask for approving the cherry-pick with cherry-pick-approved label please ?

**Comment by eparis** [comment]
/lgtm cancel
why are the insights test failing? seems that needs to be addressed.

**Comment by eparis** [comment]
So far I see base_test.go failing 4 times in the history and passing 3 times.  how are things in master? Is your flake rate 50% there?

/test insights-operator-e2e-tests

**Comment by martinkunc** [comment]
@eparis We have the same situation in master with this test. I already have an internal case to investigate it.

**Pull request merged**
