### PR TITLE
[release-4.6] Bug 1942907: Gather datahubs.installers.datahub.sap.com resources from SAP clusters

### PR DESCRIPTION
**Pull request by natiiix**
This PR is a backport of #376 and #383, which is another SAP enhancement. Much like the others, this one also has to be backported to 4.6.z for us to see any useful results in a reasonable amount of time.

The presence of the Datahubs resource(s) is used for the identification of SAP (SDI) clusters. As such, it has been decided that it should be collected from all of them in order for the team processing the IO archives to be able to tell SAP clusters apart from the remaining clusters. It is possible that all of the data gathered exclusively from SAP clusters could be missing, in which case it would be impossible to determine if a cluster has an SDI installation or not. This enhancement fixes that issue by gathering a resource that should, universally, be present on all SAP clusters. By gathering this resource, we also safely know which namespace was SDI (attempted to be) installed into.

We came up with a hopefully reasonably clear and unambiguous directory structure for custom resources (see "Sample archive" section below).

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [x] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json`

## Documentation

- `docs/gathered-data.md` - "SAPDatahubs" section

## Unit Tests

- `pkg/gather/clusterconfig/sap_datahubs_test.go` - `TestSAPDatahubs`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Changelog

No.

## References

Jira Task: https://issues.redhat.com/browse/CCXDEV-4334
Bugzilla Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1942907
`release-4.7` Backport PR: #383
Base PR: #376

### CODE REVIEW

**Comment by tremes** [comment]
I reviewed this for the 4.7 backport. I just double checked and ran it and 
/lgtm

**Comment by wking** [comment]
/retitle [release-4.6] Bug 1942907: Gather datahubs.installers.datahub.sap.com resources from SAP clusters

**Comment by tremes** [comment]
Just rebase
/lgtm

**Comment by tremes** [comment]
Just rebase
/lgtm

**Pull request merged**
