### PR TITLE
Remove "InsightsOperatorPullingSCA" TP feature check

### PR DESCRIPTION
**Pull request by tremes**
This is removing the TechPreview feature set check. IOW it means that the SCA certs will be pulled down automatically. There are also some minor enhancements in the related log messages.

This is not possible to test with cluster-bot cluster so you have to create your own cluster in AWS.

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

This requires OCP doc update

## Unit Tests

No test update

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
I can't see any issue.
/lgtm

**Review by natiiix — APPROVED** [review]
Tested on a provided testing cluster with an IO image built from this PR. It wasn't possible to test the alert itself due to the necessity to disable CVO to modify the IO image, but the alert part was tested before on a different cluster as a part of a different PR. When setting the `scaEndpoint` to a URL that returns 404, the operator status changed to `SCANotAvailable`, and then back to `AsExpected` after reseting the secret entry to the default endpoint.
/lgtm

**Pull request merged**
