### PR TITLE
add retry logic to the DVO metrics gatherer

### PR DESCRIPTION
**Pull request by tremes**
This adds retry logic (with context timeout of 2 seconds) to the DVO metrics gatherer

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

no new data

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
This is quite simple update of an existing gatherer. The tests are currently flaky so overriding.
/override ci/prow/insights-operator-e2e-tests 
/override ci/prow/e2e-gcp-ovn-techpreview

**Pull request merged**
