### PR TITLE
[release 4.7] Bug 1913343: Added changelog file

### PR DESCRIPTION
**Pull request by Sergey1011010**
Added a changelog file not including minor changes and changes before October 27.  

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample archive

No changes

## Documentation

No changes

## Unit Tests

No new unit tests

## Privacy

Not necessary

## References

https://issues.redhat.com/browse/CCXDEV-3621
https://bugzilla.redhat.com/show_bug.cgi?id=1913343
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by rluders** [comment]
I think that it is fine, but don't we want to autogenerate this CHANGELOG file? We could get this information from the PR template.

**Comment by Sergey1011010** [comment]
@rluders, I think not all the changes should be in changelog file, but only sufficient ones. We probably need to discuss that after holidays :)

**Comment by tremes** [comment]
It should be `CHANGELOG.md` and would be nice to have similar formatting (with links) as in https://github.com/openshift/cluster-monitoring-operator/blob/master/CHANGELOG.md. I would also add more for 4.6 ( at least `Adds gatherer for PodDisruptionBudget`)

**Comment by tremes** [comment]
@rluders is there some way how to autogenerate it? I agree with Sergey that we don't want everything in the changelog, but maybe it would be still possible to generate it somehow.

**Comment by rluders** [comment]
@tremes yep. It is possible to autogenete the changelog. I guess that we could even put some rules to WHAT should be included. Let me check it.

**Pull request merged**
