### PR TITLE
[release-4.8] Bug 1977754: Gather all MachineConfig definitions (#449)

### PR DESCRIPTION
**Pull request by tremes**
This changes original `SAPMachineConfig` gatherer to gather all machineconfigs definitions. We also forgot to call this new gatherer in 4.8 so this is fixing it. 

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

New data added to sample archive with:
- `docs/insights-archive-sample/config/machineconfigs/00-master.json `
- `docs/insights-archive-sample/config/machineconfigs/00-worker.json`
- ` docs/insights-archive-sample/config/machineconfigs/01-master-container-runtime.json`
-  etc.

## Documentation

Updated in:
- `docs/gathered-data.md `

## Unit Tests

Test already exists. Just minor renaming.

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
/lgtm

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
