### PR TITLE
OCPBUGS-39111: add missing permission to get nmstate CRs

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

- 

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by joselsegura — APPROVED** [review]

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
Test failures are not related. Overriding.
/override ci/prow/e2e-agnostic-upgrade
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
