### PR TITLE
NO-JIRA: manifests: bump loglevel of operator to normal

### PR DESCRIPTION
**Pull request by lance5890**
This PR implements a new data enhancement to...

with the https://github.com/openshift/insights-operator/pull/894  loglevel controller has merged, we can remove the loglevel in manifests, which now is already controlled by loglevel controller and is set on Normal by default

## Categories

- [ ] Bugfix
- [X] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- `path/to/sample_data.json`

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
@lance5890 we will need to either udpate/fix our tests or update the log level of some corresponding messages. Do you know what the default level (from the https://github.com/openshift/api/blob/master/operator/v1/types.go#L65) is equal to in terms of klog level https://github.com/kubernetes/klog/blob/main/klog.go#L1365?

**Comment by lance5890** [comment]
> we will need to either udpate/fix our tests or update the log level of some corresponding messages. Do you know what the default level (from the https://github.com/openshift/api/blob/master/operator/v1/types.go#L65) is equal to in terms of klog level https://github.com/kubernetes/klog/blob/main/klog.go#L1365?

maybe u can read this https://github.com/openshift/library-go/blob/2ad786549f07f264339f63b12b71a0fe5e77e832/pkg/operator/loglevel/util.go#L14-L25

the default operator loglevel  is Normal, which  is eqaul to v(2)

**Comment by tremes** [comment]
@lance5890 stop retesting please. We need to update the tests first as mentioned above.

**Pull request merged**
