### PR TITLE
Bug 1885261: Add new team members to OWNERS

### PR DESCRIPTION
**Pull request by natiiix**
Backport of #194, #191 and #187

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
LGTM

**Comment by bparees** [comment]
@natiiix i appreciate you following the process here, but next time you've got a change to non-shipping code like this that is definitely not a bug, just ask a pillar lead to apply the valid-bz label manually.  This BZ is going to go out as part of the list of "fixes" seen by customers which is a little weird.

**Pull request merged**
