### PR TITLE
[release-4.16] OCPBUGS-38021: Integration of the OpenStack CRs into the insights-operator

### PR DESCRIPTION
**Pull request by slawqo**
Control Plan of the Red Hat OpenStack starting from the version 18 (RHOSO 18) will be deployed using OpenShift operators as a set of OpenShift applications. Compute nodes will be deployed still as RHEL nodes and will be outside of the OpenShift cluster but all will be mangaged by the Dataplane-operator and only interface for OpenStack operators will be though the CRs:

- OpenStackControlPlane CR for the control plane,
- OpenStackDataplaneNodeSet and OpenStackDataplaneDeployment CRs for the compute nodes.

This PR adds those OpenStack CRs to the insights-operator so that whole configuration of the OpenStack control plane may be gathered by the insights-operator and send to analysis to the Insights server.

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [x] Feature
- [x] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- docs/insights-archive-sample/customresources/core.openstack.org/openstackcontrolplanes/openstack/openstack-galera-network-isolation.json
- docs/insights-archive-sample/customresources/dataplane.openstack.org/openstackdataplanedeployments/openstack/edpm-deployment.json
- docs/insights-archive-sample/customresources/dataplane.openstack.org/openstackdataplanenodesets/openstack/openstack-edpm.json

## Unit Tests

- pkg/gatherers/clusterconfig/gather_openstack_controlplanes_test.go
- pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments_test.go
- pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets_test.go

## Privacy

Anonymization functions are added and used while collecting OpenStack CRs. Anonymized data:

- OpenstackControlplanes
  - Spec.dns.template.options
- OpenstackDataplaneNodeSets
  - ansibleUser
  - edpm_sshd_allowed_ranges
  - dnsClusterAddresses
  - Status.allHostnames

## Changelog

No

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OSPRH-5904

## Additional Info

To test what data are collected by the insights-operator with those changes, OpenStack has to be deployed on top of the OpenShift cluster. The easiest way to do this is to use CRC OpenShift and [install_yamls](https://github.com/openstack-k8s-operators/install_yamls/) tool. Please follow [the guide](https://github.com/openstack-k8s-operators/install_yamls/?tab=readme-ov-file#deploy-dev-env-using-crc-edpm-nodes-with-isolated-networks) to deploy OpenStack Control Plane and OpenStackDataPlane CRs

### CODE REVIEW

**Comment by tremes** [comment]
@slawqo How far back do you want to backport this plese? I didn't know (or forget) that you wanted to backport it. I am afraid that you will need an OCPBUGS JIRA to backport.

**Comment by slawqo** [comment]
> @slawqo How far back do you want to backport this plese? I didn't know (or forget) that you wanted to backport it. I am afraid that you will need an OCPBUGS JIRA to backport.

We would like to have it in 4.16 release as this one is our target for RHOSO 18.0 GA release. I will check today this project on Jira and will open issue there.

**Comment by karelyatin** [comment]
A test fails:-
ERROR tests/data_uploaded/test_sca.py::test_periodic_check_sca - TypeError: NamespacedResource.delete() got an unexpected keyword argument 'wait'

Seems real issue and iiuc ccx-testlib version needs to be updated for 4.16, @tremes @BaiyangZhou can you check/clear this

**Comment by tremes** [comment]
Test failures are not related to these changes.
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
