### PR TITLE
OCPBUGS-19476: update Insights report config logging

### PR DESCRIPTION
**Pull request by tremes**
Do not log the complete config

## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-19476
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
Minor logging update.
/override ci/prow/e2e-metal-ipi-ovn-ipv6 
/override ci/prow/e2e-agnostic-upgrade 
/override ci/prow/e2e-gcp-ovn-techpreview

**Review by ncaak — APPROVED** [review]
/lgtm

**Pull request merged**
