### PR TITLE
OCPBUGS-45479: avoid possible Go panic when searching existing conditions

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- no new data

## Documentation

- 

## Unit Tests

- `pkg/controller/status/datagather_status_test.go` - extended to cover the problematic case

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-45479
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
linting should be fixed in #1045 
/override ci/prow/lint

**Pull request merged**
