### PR TITLE
OCPBUGS-39111: collect some nmstate customresources

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [X] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json`

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- `pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go`
- `pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-39111
https://issues.redhat.com/browse/CCXDEV-14148
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by BaiyangZhou** [comment]
IO-test failures analyze:
image

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
Test failures are about missing file in the archive, but it's not related to this change
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
