### PR TITLE
unified conditional gatherer api with targeted update edge blocking api

### PR DESCRIPTION
**Pull request by Sergey1011010**
## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

No changes

## Documentation

No changes

## Unit Tests

- `pkg/gatherers/conditional/conditional_gatherer_test.go`
- `pkg/gatherers/conditional/validation_test.go`

## Privacy

No new data was collected

## Changelog

No

## Breaking Changes

No

## References

https://issues.redhat.com/browse/CCXDEV-5878
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
Please update the PR template. I don't think this is an enhancement. Otherwise it's straightforward and looks good to me.
/retest

**Comment by Sergey1011010** [comment]
@wking, if you maybe wanted to take a look, this is the PR for unifying the APIs. We didn't reuse the code yet, just made the APIs the same (see this json https://github.com/openshift/insights-operator/pull/519/files#diff-57e9d48447e382f53bafe213301e653fd5989c354c9d751e7f6386be25459e89R39 )

**Comment by tremes** [comment]
I've already reviewed this one and it looks good to me. Thank you!
/lgtm

**Comment by tremes** [comment]
Simple rebased that was required. Thanks.
/lgtm

**Pull request merged**
