### PR TITLE
[release-4.4] Bug 1834677: Gather image registry  config

### PR DESCRIPTION
**Pull request by mfojtik**
This picks #100 on top of the refactoring changes.

This is needed so the changes from master are still pickable to release-4.4.

/cc @iNecas @martinkunc

### CODE REVIEW

**Comment by martinkunc** [comment]
I think it should be this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1834629
That is what I created from yours for backport to 4.4

**Comment by mfojtik** [comment]
@martinkunc i accidentally created new one and closed yours as dupe...

**Comment by martinkunc** [comment]
ok, sorry

**Comment by iNecas** [comment]
Seems like the test failure is relevant?

**Comment by martinkunc** [comment]
@mfojtik Could you please rebase this one once more ? There should be minimal changes I hope. Thank you!

**Comment by martinkunc** [comment]
@mfojtik Can I fork your changes and prepare a new PR to resolve the conflict ?

**Comment by martinkunc** [comment]
This is being superseeded by #131

**Pull request closed without merging**
