### PR TITLE
Bug 1967832: Adds more tests for periodic.go

### PR DESCRIPTION
**Pull request by 0sewa0**
Adds a few tests for `periodic.go` (+ some minor lint fixes)

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [x] Others (CI, Infrastructure, Documentation)

## Sample Archive

- not necessary

## Documentation

- not necessary

## Unit Tests

- `pkg/controller/periodic/periodic_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

### CODE REVIEW

**Comment by tremes** [comment]
@0sewa0 please rebase.

**Review by rluders — APPROVED** [review]
The code inside the `Test_Controller_Run` is a little bit messy, IMHO, but I have no good idea how to improve it... in this case.

/lgtm

**Pull request merged**
