### PR TITLE
NO-JIRA: limit the time for the new rapid container logs & update the endpoint

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

-

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
the test failure is not related to this PR. it's about some missing config map data in the archive.
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
