### PR TITLE
Use github.com/eparis/urlhash to anonymize URLs

### PR DESCRIPTION
**Pull request by eparis**
It should give us stable values of ip addresses and URLs but not actually leak
customer data. This isn't simple to work backwards to the original IP because
the values are salted with a random string.

Input:  https://my.openshift-console-ingress.api.console.customer.com/path/to/something/openshift
Output: https://05.openshift-console-5bd922e.api.console.ee8ca6dd.com/b5bf/39/ca74813cb/openshift

Input:  https://127.0.0.1
Output: https://04c.7e9.7e9.b4b

Input:  https://127.0.0.2
Output: https://04c.7e9.7e9.b35

This also attempts to keep things like 'http://' or 'https://'.
It also will retain certain words in URLs, like openshift, or console.
It also represent ip addresses a bit wierdly, since you get 3 hex characters, but you can make
useful comparisions between hashed values.

### CODE REVIEW

**Comment by eparis** [comment]
A cluster with this running can be found at 5318290/cd 626bd7fe-6591-4ace-b863-1dca7442b040/ for someone who wants to look at the results..

**Comment by eparis** [comment]
/retest
failure that aws said the ignition bucket didn't exist

**Comment by alexandrevicenzi** [comment]
@eparis this PR has conflicts and is stale for a long time, Do you care to fix it? Is there a BZ issue related to this?

**Comment by tremes** [comment]
@eparis any update on this pls?

**Pull request closed without merging**
