### PR TITLE
[release 4.6] Bug 1887759: Adds MachineConfigPool gatherer

### PR DESCRIPTION
**Pull request by 0sewa0**
Backports (4.6) a new data enhancement for gathering MachineConfigPools.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [X] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/config/machineconfigpools/master.json`
- `docs/insights-archive-sample/config/machineconfigpools/worker.json`

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- `pkg/gather/clusterconfig/clusterconfig_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/CCXDEV-3285
https://issues.redhat.com/browse/INSIGHTOCP-84
https://bugzilla.redhat.com/show_bug.cgi?id=1887759

### CODE REVIEW

**Comment by tremes** [comment]
Verified on QuickLab clusters. We should just doublecheck the permission for the new apiGroup.
/lgtm

**Comment by tremes** [comment]
@sdodson Can you please take a look at this one and add cherry-pick approved label please?

**Comment by sdodson** [comment]
Does this in any way impact cluster stability or upgrade success?

**Comment by sdodson** [comment]
(Patch Manager) This PR was reviewed for inclusion last week, however this adds feature work during the weeks immediately after release where we're focused on stability, upgrade success, and anything which blocks backports of critical customer impacting bugs. Since this doesn't meet those criteria it was not accepted last week and likely will not until we've been able to promote the 4.5 to 4.6 upgrade to the stable channel.

**Comment by sferich888** [comment]
@sdodson if PX approves backports like, this would that help unstick this PR's current state?

**Comment by tremes** [comment]
Verified again. Works as expected.
/lgtm

**Pull request merged**
