### PR TITLE
CCXDEV-11946: finalize the config update to the new config map

### PR DESCRIPTION
**Pull request by tremes**
This finalizes the move of configuration from the legacy `support` secret to a new `insights-config` config map. 
The configmap definition can look like:
```yaml
data:
  config.yaml: |
    dataReporting:
      interval: 30m
      obfuscation:
      - workload_names
      - networking
    sca:
      disabled: false
    alerting:
      disabled: false
    proxy:
      httpProxy: http://example.com
      httpsProxy: https://example.com
      noProxy: test.org
    clusterTransfer:
      interval: 1h
```

The operator logs every config change and it looks like:
```
periodic.go:257] Configuration is 
	dataReporting:
		interval: 30m0s,
		uploadEndpoint: https://console.redhat.com/api/ingress/v1/upload,
		storagePath: /var/lib/insights-operator,
		downloadEndpoint: https://console.redhat.com/api/insights-results-aggregator/v2/cluster/%s/reports, 
		conditionalGathererEndpoint: https://console.redhat.com/api/gathering/gathering_rules,
		obfuscation: [workload_names networking]
	sca:
		disabled: false,
		endpoint: https://api.openshift.com/api/accounts_mgmt/v1/certificates,
		interval: 8h0m0s
	alerting:
		disabled: false
	clusterTransfer:
		endpoint: https://api.openshift.com/api/accounts_mgmt/v1/cluster_transfers/,
		interval: 1h0m0s
	proxy:
		httpProxy: http://example.com,
		httpsProxy: https://example.com,
		noProxy: test.org

```

## Categories`

- [ ] Bugfix
- [ ] Data Enhancement
- [X] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

no new data

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
I think this is not 100% at the moment.
/hold

**Review by rluders — APPROVED** [review]
Tested and seems good. 
/lgtm

**Comment by JoaoFula** [comment]
why is  jira/valid-reference still being required?

**Pull request merged**
