### PR TITLE
[release 4.6] Bug 1889676: Gather installplans

### PR DESCRIPTION
**Pull request by 0sewa0**
A backport(4.6) of a new data enhancement for gathering of installplans.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [X] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/config/instalplans.json`

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- `pkg/gather/clusterconfig/clusterconfig_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/CCXDEV-3329
https://issues.redhat.com/browse/INSIGHTOCP-75
https://bugzilla.redhat.com/show_bug.cgi?id=1889676

### CODE REVIEW

**Comment by sdodson** [comment]
(Patch Manager) This PR was reviewed for inclusion last week, however this adds feature work during the weeks immediately after release where we're focused on stability, upgrade success, and anything which blocks backports of critical customer impacting bugs. Since this doesn't meet those criteria it was not accepted this week and likely will not until we've been able to promote the 4.5 to 4.6 upgrade to the stable channel.

**Comment by sferich888** [comment]
@sdodson if PX approves backports like, this would that help unstick this PR's current state?

**Comment by tremes** [comment]
This is our new PR template proposal that will be applied once there's an agreement. 
**1. Is this PR just for IO enhancement or there are more changes?**
Just enhancement. The change in `config/local.yaml ` is just for local development. These values are overwritten by "support" secret in prod. 
**2. Was there a unit test?**
Yes - see the change in `pkg/gather/clusterconfig/clusterconfig_test.go`  
**3. What are related references for this PR?**
https://issues.redhat.com/browse/INSIGHTOCP-75
https://bugzilla.redhat.com/show_bug.cgi?id=1855706
https://access.redhat.com/solutions/5221881

**4. Has data anonymization/privacy been considered by CCX? (e.g. external IP addresses)**
Yes. There are no sensitive data in the newly collected information
**5. Are these changes reflected in the sample archive and documentation?**
Yes - see the changes in `docs/gathered-data.md` and `docs/insights-archive-sample/config/instalplans.json `

**Comment by tremes** [comment]
I installed 3 OLM operators to `openshift-operators` namespace. This produced 3 new installplans, which were correctly gathered. 
/lgtm

**Pull request merged**
