### PR TITLE
OCPBUGS-35882: properly encode the URL for the advisor links

### PR DESCRIPTION
**Pull request by tremes**
Previously when user clicked on the link and there wasn't any active SSO session/token then the redirect failed. 

## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- no new data

## Documentation

- 

## Unit Tests

- `
## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-35882
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
I forgot to update this one failing test. It was already fixed.
/override ci/prow/e2e-gcp-ovn-techpreview

**Pull request merged**
