### PR TITLE
Update K8s & OpenShift versions + vendoring

### PR DESCRIPTION
**Pull request by tremes**
Version update

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by rluders** [comment]
@tremes could you please also update the golang version for `debug.Dockerfile`?

**Comment by tremes** [comment]
Just version updates.
/label px-approved
/label docs-approved
/label qe-approved

**Pull request merged**
