### PR TITLE
Reduce binary file size

### PR DESCRIPTION
**Pull request by rluders**
This PR reduces the binary file by ~28% stripping the DWARF tables needed for debuggers. Stack traces and panics still readable and valid. It is NOT a compression, so, should not cause any overhead.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample archive

No.

## Documentation

No.

## Unit Tests

No.

## Privacy

Not applicable.

## Changelog

No.

## References

Not applicable.

### CODE REVIEW

**Comment by tremes** [comment]
Why do we need a smaller binary? I can't see any advantage TBH and when looking quickly at the flags https://stackoverflow.com/questions/22267189/what-does-the-w-flag-mean-when-passed-in-via-the-ldflags-option-to-the-go-comman it seems it will disable pprof.

**Comment by rluders** [comment]
@tremes are we profiling on production as well?

**Comment by tremes** [comment]
@rluders We don't as I mentioned today. My point was that now it's pretty easy to turn on the profiling (and I guess it was added on purpose). After this change it means one needs to build a new image to be able to turn it on AFAIK. I think I would prefer the original behavior when comparing it to just smaller binary.

**Comment by smarterclayton** [comment]
We have actually asked that people stop stripping binaries now, because go versions have made the cost cheaper.

**Pull request closed without merging**
