### PR TITLE
Bug 1917371: Adds docs for using the profiler

### PR DESCRIPTION
**Pull request by 0sewa0**
Adds docs for using the profiler within IO.

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [x] Others (CI, Infrastructure, Documentation)

## Sample archive

Just docs update

## Documentation

- yeeeeep

## Unit Tests

Just docs update

## Privacy

Just docs update

## Changelog

Not necessary

## References

none

### CODE REVIEW

**Review by rluders — APPROVED** [review]
/lgtm

**Review by Sergey1011010 — APPROVED** [review]
/lgtm

**Pull request merged**
