### PR TITLE
Bug 1982170: Set also the summary operation when updating status

### PR DESCRIPTION
**Pull request by tremes**
Set also to operation so it can be distinguished in `status.go`. See the messy code here https://github.com/openshift/insights-operator/blob/master/pkg/controller/status/status.go#L156. We should probably set `degradingFailure` to false by default. There's already issue to refactor this method. 

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

No doc update

## Unit Tests

No new test but we should think about some integration test if possible. 

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=1982170
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by natiiix — APPROVED** [review]
Didn't test locally because this is just a simple fix.
/lgtm

**Review by tisnik — APPROVED** [review]
Seems legit!

**Pull request merged**
