### PR TITLE
Bug 1821149: Cherry-pick release 4.3 Support for specific http proxy for the service

### PR DESCRIPTION
**Pull request by martinkunc**
Applied same commits as in #87

### CODE REVIEW

**Comment by martinkunc** [comment]
@jwforres Could I ask for approving the cherry-pick with cherry-pick-approved label please ?

**Comment by jwforres** [comment]
> @jwforres Could I ask for approving the cherry-pick with cherry-pick-approved label please ?

Patch manager changes weekly. The current patch manager will look for any PRs that are ready to merge on Wednesday to Friday. This PR is currently not ready for patch manager approval since it still has invalid bug labels. Patch managers will not override bugzilla labels unless it is an exceptional circumstance. Please get QE to verify your bug in 4.4 and then refresh your bugzilla labels.

**Comment by russellb** [comment]
@martinkunc Hi, I'm the patch manager this week.

I'm pretty confused by this PR.  It references the 4.5 and 4.4 versions of the PR, but the commits in each don't line up.  4.5 had 7 commits, 4.4 had 10, and then this one has 9?  Can you take a look at cleaning up the commit history here?

**Pull request merged**
