### PR TITLE
Bug 1837967: Gathering Image Pruner configuration

### PR DESCRIPTION
**Pull request by ricardomaraschini**
Adding cluster's Image Registry pruner configuration to gather.

### CODE REVIEW

**Comment by dmage** [comment]
/lgtm

/cc @iNecas @martinkunc
This is a new config for the automated image pruner that was added in 4.4.

**Comment by martinkunc** [comment]
Hi Ricardo, should this be explicitly gathered only for 4.5, or does image-pruner exist in 4.4,4.3 or 4.2 ? Do you know ?
For better maintainability we should try to merge in older versions. I have other PRs which should be resolved before this will go smoothly. I could do it afterwards, if that would make sense to collect even in older versions.

**Comment by ricardomaraschini** [comment]
> Hi Ricardo, can it be merged into 4.4 as well ?
> For better maintainability we should try to merge in older versions. There is #101 which should be merged before this will go smoothly. I could do it afterwards, if that would make sense to collect even there.

@martinkunc We need this backported to 4.4 as well. As you mentioned we need to wait for https://github.com/openshift/insights-operator/pull/113 to be merged first but that one seems to be closed.

Could you clarify?

**Comment by martinkunc** [comment]
> > Hi Ricardo, can it be merged into 4.4 as well ?
> > For better maintainability we should try to merge in older versions. There is #101 which should be merged before this will go smoothly. I could do it afterwards, if that would make sense to collect even there.
> 
> @martinkunc We need this backported to 4.4 as well. As you mentioned we need to wait for #113 to be merged first but that one seems to be closed.
> 
> Could you clarify?

@ricardomaraschini Sorry, we need to wait for #103 to be merged to 4.4 before this one.

**Pull request merged**
