### PR TITLE
dockerfile for remote debugging

### PR DESCRIPTION
**Pull request by Sergey1011010**
Dockerfile to build a container with a debugger inside which you can remotely connect to

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

No

## Documentation

No

## Unit Tests

No 

## Privacy

No new data collected

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???
https://docs.engineering.redhat.com/display/CCXDEV/How+to+debug+a+remote+pod

### CODE REVIEW

**Review by rluders — CHANGES_REQUESTED** [review]
It looks good. I'm just wondering if we can't have some building image commands added to the Makefile... Can we? :) Check [this one](https://github.com/sumelms/microservice-account/pull/13).

**Comment by Sergey1011010** [comment]
@rluders yeah, we could add something like this

**Comment by Sergey1011010** [comment]
Totally forgot about it. @rluders added a makefile entry

**Review by natiiix — APPROVED** [review]
/lgtm
I haven't tested it because I don't really have a suitable cluster, but this shouldn't break anything important.

**Pull request merged**
