### PR TITLE
Add OCP versions to particular gatherers

### PR DESCRIPTION
**Pull request by tremes**
Update formatting of our gatherers doc & add known OCP versions to some gatherers. 

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample archive

No new data

## Documentation

Documentation updated in:
- `docs/gathered-data.md `

## Unit Tests

No unit test

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
@jholecek-rh Please check.

**Comment by tremes** [comment]
You can check preview in https://github.com/tremes/insights-operator/blob/my-master/docs/gathered-data.md

**Comment by 0sewa0** [comment]
where no versions are specified those were present "from the start"

**Comment by tremes** [comment]
Yeah so I think I am done. I think I won't be able to find more.

**Comment by jholecek-rh** [comment]
@tremes I love it! https://github.com/tremes/insights-operator/blob/my-master/docs/gathered-data.md is exactly what I hoped for.

If you can guarantee that new changes will be covered in the docs like this, we don't need the script that fetches the data. Or you will need it to keep this data up to date?

**Comment by tremes** [comment]
@jholecek-rh Well this was manual work based on the script output. We can think about next steps (wrt some automation). We can try to guarantee an update, but note that it is always necessary for the corresponding errata to exist.

**Comment by jholecek-rh** [comment]
I understand that it was manual work. By "guarantee" I meant at the process level - make it a standard part of the docs.

I'm not sure what is the problem with "errata has to exist". If you mean to say that there are cases where we cannot tell which OCP version a data enhancement landed in, we need to take this discussion one level up.  :)

**Comment by 0sewa0** [comment]
/lgtm

I like it, it clears things up, however I dread how we are going to keep these up to date :sob:

**Pull request merged**
