### PR TITLE
Do not use the kube-rbac-proxy container

### PR DESCRIPTION
**Pull request by tremes**
This removes the `kube-rbac-proxy` container, which is not necessary as we learned. 

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by natiiix — APPROVED** [review]
Looking at the code, everything looks fine. It is mostly a revert after a careful consideration of some recently uncovered facts regarding the changes we made to how we report metrics.
/lgtm

**Comment by tremes** [comment]
This is basically a revert of the https://github.com/openshift/insights-operator/pull/637/, because we found out that the kube-rbac-proxy container is not required. Adding the remaining labels.
/label docs-approved
/label px-approved

**Pull request merged**
