### PR TITLE
[release-4.13] OCPBUGS-12618: update golang.org/x/net version

### PR DESCRIPTION
**Pull request by tremes**
This PR implements a new data enhancement to...

## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

no new data

## Documentation

no docs

## Unit Tests

no new test

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-12618
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]

**Comment by JoaoFula** [comment]
Failing test has been corrected. Retesting

**Pull request merged**
