### PR TITLE
Bug 1925408: Remove StatefulSet gatherer & replace it with gathering "cluster-mon…

### PR DESCRIPTION
**Pull request by tremes**
…itoring-config" config map

This removes original `StatefulSet` gatherer. The information can be obtained from `cluster-monitoring-config` config map. 

## Categories

- [X] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

**TODO**

## Documentation

**TODO**

## Unit Tests

No new test

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/CCXDEV-3970
https://issues.redhat.com/browse/INSIGHTOCP-51
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by 0sewa0** [comment]
would it make sense to have the stateful-set gathering in its own file and its own gathering function ?

**Comment by tremes** [comment]
@0sewa0 We don't need `StatefulSet` gathering for anything as far as I know.

**Comment by 0sewa0** [comment]
@tremes I meant the `gatherMonitoringCM` part

**Comment by tremes** [comment]
@0sewa0 `gatherMonitoringCM` is gathering just another configmap. I can't see any advantage of having it in its own file TBH. I think it's better to keep gatherting of the same resources in one gatherer if possbile. I guess I don't want to have e.g `config_maps_1.go` for let's say config maps from `openshift-config` namespace and `config_maps_2.go` for config maps from some other namespace.

**Comment by 0sewa0** [comment]
@tremes  that makes sense, thx :)
the code looks good, maybe the names at https://github.com/openshift/insights-operator/pull/329/files#diff-384b761d21c5b0abe263caf445c6c026d977784e53da51915369f8daf39e4d6dR37 could use an update to something similar 1 line under that

**Review by natiiix — APPROVED** [review]
Tested locally against a shared OCP 4.6 cluster on QuickLab.

The gathered archive contained the `config/configmaps/openshift-monitoring/cluster-monitoring-config/config.json` file as advertised.

/lgtm

**Pull request merged**
