### PR TITLE
Bug 1907293: e2e tests - increase timeouts little bit

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample archive

- `path/to/sample_data.json`

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

### CODE REVIEW

**Review by Sergey1011010 — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
@eparis Can we merge this without creating a bz please? This is just increasing timeouts in tests.

**Review by psimovec — APPROVED** [review]
With the added change of checker interval to 4 minutes, I can give lgtm
/lgtm

**Pull request merged**
