### PR TITLE
test(clusterconfig): Unit tests for openshift sdn logs gatherer

### PR DESCRIPTION
**Pull request by ncaak**
This PR implements a simple unit test for SDN logs gatherer

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

- N/A

## Documentation

- N/A

## Unit Tests

- `pkg/gatherers/clusterconfig/gather_openshift_sdn_logs_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Changelog

Pending

## Breaking Changes

No

## References

https://issues.redhat.com/browse/CCXDEV-10125

### CODE REVIEW

**Review by rluders — APPROVED** [review]
/lgtm

**Comment by ncaak** [comment]
Cancelling this PR to summarize Log Gatherers changes in the same PR.
Merged changes into #751

**Pull request closed without merging**
