### PR TITLE
Updating the owners list

### PR DESCRIPTION
**Pull request by tremes**
Bye bye Marcell!!!

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

No doc

## Unit Tests

No new tests

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by natiiix — APPROVED** [review]
Bye bye! :wave: :disappointed:

**Review by natiiix — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
Waiting for https://github.com/openshift/origin/pull/26264
/hold

**Pull request merged**
