### PR TITLE
NO-JIRA: add/update some missing sample data

### PR DESCRIPTION
**Pull request by tremes**
This PR implements a new data enhancement to...

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

- `docs/insights-archive-sample/config/certificatesigningrequests/csr-test.json`

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- 

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
Here's no change of any logic. Test failures are not relevant.
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
