### PR TITLE
OCPBUGS-41932: set the RemoteConfigurationAvailable and RemoteConfigu…

### PR DESCRIPTION
**Pull request by tremes**
…rationValid clusteroperator conditions in disabled cluster

## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- no new data

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-41932
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
@ncaak please review
/assign @ncaak

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
The one test error is a known issue and not related to this change.
/override ci/prow/insights-operator-e2e-tests

**Pull request merged**
