### PR TITLE
OCPBUGS-5347: do not periodically update Available clusteroperator co…

### PR DESCRIPTION
**Pull request by tremes**
…ndition in disabled state

It doesn't make any sense to set some other conditions in disabled state, because it's still "healthy" state from operator perspective. Temporarily setting a different  `Available` condition status caused the "since" time reset every 2 mins and unnecessarily updated the transition time of the condition:

```
oc get co insights --watch
NAME       VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
insights   4.13.0-ec.1   True        False         False      62s     
insights   4.13.0-ec.1   True        False         False      1s      
insights   4.13.0-ec.1   True        False         False      0s      
insights   4.13.0-ec.1   True        False         False      1s      
insights   4.13.0-ec.1   True        False         False      0s      
insights   4.13.0-ec.1   True        False         False      0s      
```

## Categories

- [X] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

no new data

## Unit Tests

extended 
- `pkg/controller/status/controller_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/OCPBUGS-5347
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
Yep, it makes sense.
/lgtm

**Comment by tremes** [comment]
I found out that this is still not 100% in case when operator is degraded and then marked as disabled.
/hold

**Pull request merged**
