### PR TITLE
K8s & OpenShift version updates

### PR DESCRIPTION
**Pull request by tremes**
This PR implements a new data enhancement to...

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by rluders** [comment]
Tested, it works as expected.
/lgtm

**Comment by tremes** [comment]
This is just version update.
/label qe-approved
/label px-approved
/label docs-approved

**Pull request merged**
