### PR TITLE
AUTH-481: Add PSa labels to openshift-insights namespace

### PR DESCRIPTION
**Pull request by liouk**
This PR adds the required PSa labels in the `openshift-insights` namespace.

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)
## Breaking Changes

No breaking changes; `restricted` is the default.

## References

https://issues.redhat.com/browse/AUTH-481

### CODE REVIEW

**Comment by liouk** [comment]
/hold
blocked by https://issues.redhat.com/browse/AUTH-482

**Comment by tremes** [comment]
@liouk what is the status of this one please? Still blocked?

**Comment by liouk** [comment]
@tremes yes, this is still blocked. I'll remove stale for now.

/remove-lifecycle stale

**Pull request closed without merging**
