### PR TITLE
[release-4.6] Bug 1935574: Extend the OLM operator data with related …

### PR DESCRIPTION
**Pull request by tremes**
…ClusterServiceVersion conditions

Getting more data about installed OLM operators and create corresponding upgrade report is one of the CCX goals. This PR adds the new gatherer to collect information (name, version and conditions) about installed OLM operators. See the CCX epics below.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

Updated in:
- `docs/insights-archive-sample/config/olm_operators.json`

## Documentation

The documentation updated in:
- `docs/gathered-data.md`

**THERE ARE MORE UPDATES TO FIX SOME MISSING STUFF AND THE ORDERING**. The doc is generated so it shouldn't hopefully cause conflicts in the future. 

## Unit Tests

New unit test in:
- `pkg/gather/clusterconfig/olm_operators_test.go `

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/CCXDEV-719
https://issues.redhat.com/browse/CCXDEV-3965
https://issues.redhat.com/browse/CCXDEV-3966
https://bugzilla.redhat.com/show_bug.cgi?id=1935574
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by 0sewa0** [comment]
/lgtm
Tested it on a cluster-bot cluster, where I deployed my experimental OLM insights-operator to be collected.
```
[
    {
        "name": "insights-operator.default",
        "version": "v0.0.2",
        "csv_conditions": [
            {
                "lastTransitionTime": "2021-03-29T09:11:30Z",
                "lastUpdateTime": "2021-03-29T09:11:30Z",
                "message": "requirements not yet checked",
                "phase": "Pending",
                "reason": "RequirementsUnknown"
            },
            {
                "lastTransitionTime": "2021-03-29T09:11:30Z",
                "lastUpdateTime": "2021-03-29T09:11:30Z",
                "message": "one or more requirements couldn't be found",
                "phase": "Pending",
                "reason": "RequirementsNotMet"
            },
            {
                "lastTransitionTime": "2021-03-29T09:11:30Z",
                "lastUpdateTime": "2021-03-29T09:11:30Z",
                "message": "all requirements found, attempting install",
                "phase": "InstallReady",
                "reason": "AllRequirementsMet"
            },
            {
                "lastTransitionTime": "2021-03-29T09:11:30Z",
                "lastUpdateTime": "2021-03-29T09:11:30Z",
                "message": "waiting for install components to report healthy",
                "phase": "Installing",
                "reason": "InstallSucceeded"
            },
            {
                "lastTransitionTime": "2021-03-29T09:11:30Z",
                "lastUpdateTime": "2021-03-29T09:11:30Z",
                "message": "installing: waiting for deployment insights-operator to become ready: Waiting for deployment spec update to be observed...\n",
                "phase": "Installing",
                "reason": "InstallWaiting"
            },
            {
                "lastTransitionTime": "2021-03-29T09:11:42Z",
                "lastUpdateTime": "2021-03-29T09:11:42Z",
                "message": "install strategy completed with no errors",
                "phase": "Succeeded",
                "reason": "InstallSucceeded"
            }
        ]
    }
]
```

**Comment by tremes** [comment]
@russellb Hi, there was only documentation rebase. We maintain the documentation for the gather data and there was some conflict. Can you please approve again?

**Comment by russellb** [comment]
@tremes it's in conflict now.  It'll have to wait for next week

**Comment by tremes** [comment]
Ohhh again. OK

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

**Pull request merged**
