### PR TITLE
Fix error in default Smart proxy report endpoint

### PR DESCRIPTION
**Pull request by joselsegura**

### CODE REVIEW

**Review by rluders — APPROVED** [review]
/lgtm

**Comment by rluders** [comment]
BTW, I'm surprised that these values are fixed in code and not coming from some configmap or somethig. :thinking:

**Comment by joselsegura** [comment]
> BTW, I'm surprised that these values are fixed in code and not coming from some configmap or somethig. thinking

It can be read from the `configobserver` package too from the cluster secrets, or by the configuration parser in the configuration file... but the default one if all of them are missing is incorrect, that leads in an IO that cannot retrieve the report

**Comment by rluders** [comment]
> all of them are missing is incorrect, that leads in an IO that cannot retrieve the

I see. That makes sense.

**Pull request merged**
