### PR TITLE
Bump k8s & OpenShift versions

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

No doc update

## Unit Tests

One test updated because of linting check

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by natiiix — APPROVED** [review]
Obviously, I haven't looked through the individual changes, but I tried building and running the updated IO locally, and I haven't encountered any abnormality once I've properly upgraded my Go installation to 1.17, so I believe everything is alright. Thank you for the update!
Perhaps it would be a good idea to add at least a bit of context into the PR description.
/lgtm

**Comment by tremes** [comment]
Well this doesn't work....
/hold

**Review by natiiix — APPROVED** [review]
Thanks for noticing the issue with the logging flags. Hopefully it will work properly now.
/lgtm

**Pull request merged**
