### PR TITLE
[release-4.8] Bug 1967949: MemoryRecord name can be obfuscated & fix case of duplicate records (…

### PR DESCRIPTION
**Pull request by tremes**
…#444)

This is fix for clearing map of the records and proper way of naming and comparing the keys in the map. This is pretty important since the max data size is now strictly limited and without this fix it will grow infinitely (especially when obfuscation is enabled)

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

No update

## Unit Tests

Tests added and updated in:

- `pkg/recorder/recorder_test.go `

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
Just bp... seems good.
/lgtm

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Pull request merged**
