### PR TITLE
Bug 1879068: Collect hostsubnet information

### PR DESCRIPTION
**Pull request by tremes**
Gather host subnet information and anonymize all the IP addresses. The important/interesting part is the number of Egress IPs that can be obtained from this.

### CODE REVIEW

**Comment by tremes** [comment]
@natiiix, @martinkunc, @iNecas can you please review?

**Comment by iNecas** [comment]
What information exactly we're looking for here and why?

In general, we consider ip addresses and sensitive data and anonymize (see https://github.com/openshift/insights-operator/blob/3b7ba28926b16f5513ba8302613f7b2b31db76d8/pkg/gather/clusterconfig/clusterconfig.go#L1050) unless confirmed explicitly that it's not introducing security risk and justified that we really need the info.

**Comment by tremes** [comment]
@iNecas Yep thanks. I realized I should anonymized that in sense of providing only count of egressIPs. I'll update.

**Comment by tremes** [comment]
Anonymized and Updated.

**Review by natiiix — APPROVED** [review]
/lgtm

**Pull request merged**
