### PR TITLE
add testify and insights-operator-utils dependencies to make tests more clear

### PR DESCRIPTION
**Pull request by Sergey1011010**
This PR adds testify and insights-operator-utils which are needed for https://github.com/openshift/insights-operator/pull/273 but also can be helpful to make other unit-tests more clear

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

No changes

## Documentation

No changes

## Unit Tests

No changes

## Privacy

No new data is collected

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]

**Review by rluders — CHANGES_REQUESTED** [review]
It only adds the dependencies. Where is the code that uses it?

/lgtm cancel

**Comment by Sergey1011010** [comment]
@rluders, yup, there's an example https://github.com/openshift/insights-operator/pull/273/files#diff-e4138d3ef961ea73d03fab7ae46996a68fc6cb576f07cb00946f84cad9a5ba5bR34

**Comment by rluders** [comment]
> @rluders, yup, there's an example https://github.com/openshift/insights-operator/pull/273/files#diff-e4138d3ef961ea73d03fab7ae46996a68fc6cb576f07cb00946f84cad9a5ba5bR34

In this case, should be this dependencies added by the #273 ?

**Pull request closed without merging**
