### PR TITLE
[release-4.9] Bug 2026644: Gather all the container logs from relate namespaces of degraded clusteroperator

### PR DESCRIPTION
**Pull request by tremes**
This is backport of https://github.com/openshift/insights-operator/pull/516 + update of deprecated `ioutil` 

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [X] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

- `path/to/sample_data.json`

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/CCXDEV-6467
https://bugzilla.redhat.com/show_bug.cgi?id=2026644
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by natiiix — APPROVED** [review]
It's a backport, so I only looked through the code and check locally that it runs fine and generated a valid archive without a more thorough investigation of the gatherer itself.
/lgtm
Edit: Could you maybe update the PR description a bit?

**Comment by tremes** [comment]
@JoaoFula Obrigado!

**Pull request merged**
