### PR TITLE
Add Pavel Tisnovsky into list of repo owners

### PR DESCRIPTION
**Pull request by tisnik**

### CODE REVIEW

**Comment by tisnik** [comment]
@lina-nikiforova I assume that after https://github.com/openshift/insights-operator/pull/61 will be merged, the tests will be ok (passing), right? :)

**Comment by lina-nikiforova** [comment]
@tisnik I believe so, we will see in #61 as the tests were restarted :)

**Comment by lina-nikiforova** [comment]
@tisnik yes, it passed there :)

**Pull request merged**
