### PR TITLE
[release 4.7] Bug 1960645: Adds virt_platform metric to the collected metrics

### PR DESCRIPTION
**Pull request by 0sewa0**
Backports the following feature to 4.7:
Adds virt_platform metric to the collected metrics, this metric is present on every cluster, so testing can be done on a fresh cluster-bot cluster.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/config/metrics` updated

## Documentation

- `docs/gathered-data.md` updated

## Unit Tests

-  not necessary

## Privacy

Yes. There are no sensitive data in the newly collected information.

### CODE REVIEW

**Comment by rluders** [comment]
Just checking the code, looks pretty simple.
/lgtm

**Comment by sdodson** [comment]
(patch-manager) I skipped over this one because it's not clear to me where this was backported from, please reference the upstream PR. When I go looking for why there was an additional commit necessary to fix the tests I cannot find the origin of that commit on master branch because tests were moved to an internal repo, see https://github.com/openshift/insights-operator/pull/387

This makes it very hard to verify backports.

**Comment by 0sewa0** [comment]
@sdodson the upstream PR: https://github.com/openshift/insights-operator/pull/427
The update to the e2e tests were needed because the e2e tests for 4.7 and earlier still use the in-repo e2e tests which are not that reliable (the move to python e2e testing in a separate repo was done because of this) and not really maintained. These tests are removed(ported to python) in upstream. 
The e2e tests were failing because of the configmaps gatherer gathered some files that the e2e test wasn't prepared for, so the test failures had nothing to do with the original contents of this PR. (+ this only happened on the CI cluster, when I ran the e2e tests locally against a cluster-bot cluster the tests pasted without an issue)
After waiting/hoping for 3 days that the CI will magically pass, I had to update the test because of the urgency/importance of this PR.

**Pull request merged**
