### PR TITLE
[release 4.5] Bug 1887763: Adds MachineConfigPool gatherer

### PR DESCRIPTION
**Pull request by 0sewa0**
Backports (4.5) a new data enhancement for gathering MachineConfigPools.

## Categories

- [ ] Bugfix
- [X] Enhancement
- [X] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample archive

- `docs/insights-archive-sample/config/machineconfigpools/master.json`
- `docs/insights-archive-sample/config/machineconfigpools/worker.json`

## Documentation

- `docs/gathered-data.md`

## Unit Tests

- `pkg/gather/clusterconfig/clusterconfig_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## References

https://issues.redhat.com/browse/CCXDEV-3285
https://issues.redhat.com/browse/INSIGHTOCP-84
https://bugzilla.redhat.com/show_bug.cgi?id=1887763

### CODE REVIEW

**Comment by sferich888** [comment]
@mklika & @radekvokal this needs to have a peer review

**Comment by tremes** [comment]
I verified this locally and `MachineConfigPool` definitions are gathered correctly.
/lgtm

**Pull request merged**
