### PR TITLE
Introduce parallelism to unit tests

### PR DESCRIPTION
**Pull request by rluders**
This PR implements parallelism to our unit tests to improve its performance.

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample archive

No.

## Documentation

No.

## Unit Tests

- `pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go` - this one can't use parallelism
- `pkg/config/configobserver/configobserver_test.go`
- `pkg/controller/status/status_test.go`
- `pkg/gather/clusterconfig/0_gahterer_test.go`
- `pkg/gather/clusterconfig/certificate_signing_requests_test.go`
- `pkg/gather/clusterconfig/config_maps_test.go`
- `pkg/gather/clusterconfig/image_pruners_test.go`
- `pkg/gather/clusterconfig/image_registries_test.go`
- `pkg/gather/clusterconfig/install_plans_test.go`
- `pkg/gather/clusterconfig/service_accounts_test.go`

## Privacy

This PR doesn't collect any data or change any gather.

## Changelog

No.

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
@psimovec or @quarckster please check

**Review by quarckster — APPROVED** [review]
LGTM

**Review by quarckster — APPROVED** [review]

**Comment by psimovec** [comment]
Usage of parallelism seems reasonable to me and LGTM.

I have one nitpick unrelated to changes in this PR - about the file you are changing.. pkg/gather/clusterconfig/0_~gahterer~_test.go -> pkg/gather/clusterconfig/0_**gatherer**_test.go

But as it is unrelated to the changes you made, I let you decide if you want to change it in this PR.

/lgtm

**Pull request merged**
