### PR TITLE
Insightsclient metrics - small bugfix , added status code '0'.

### PR DESCRIPTION
**Pull request by SamuelStuchly**
Metric insightsclient_request_send would output nothing if the request build failed. Now it will output status code '0' to indicate request build failure, so these cases are recorded in metrics and later telemeter as well.

### CODE REVIEW

**Comment by iNecas** [comment]
Will need rebase after https://github.com/openshift/insights-operator/pull/26/

**Comment by iNecas** [comment]
Rebase needed to update the name of the metric

**Comment by SamuelStuchly** [comment]
[test]

**Comment by alexandrevicenzi** [comment]
@SamuelStuchly can you rebase this?

**Pull request closed without merging**
