### PR TITLE
Minor gathering docs update

### PR DESCRIPTION
**Pull request by tremes**
Updating OCP versions for the cost metrics gatherer

## Categories

- [ ] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

- `docs/gathered-data.md`

## Unit Tests

No new test

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by rluders — APPROVED** [review]
/lgtm

**Review by natiiix — APPROVED** [review]
I'm a few minutes too late, but I'll add my approval as well since I've already looked at the PR anyways.

**Pull request merged**
