### PR TITLE
Implement periodic gathering as a job in tech preview

### PR DESCRIPTION
**Pull request by tremes**
This reopen of https://github.com/openshift/insights-operator/pull/764 with adding resource requests. Please check the description of the original PR. 

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [X] Feature
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

no new data

## Documentation

- `path/to/documentation.md`

## Unit Tests

- `path/to/file_test.go`

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

Yes/No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Comment by tremes** [comment]
/periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-arm64-techpreview

**Comment by tremes** [comment]
//payload-job periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-arm64-techpreview

**Comment by tremes** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.14-ocp-e2e-aws-ovn-arm64-techpreview

**Comment by tremes** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Review by ncaak — APPROVED** [review]
/lgtm

Although there are couple of places like [gather_commands Gather function](https://github.com/openshift/insights-operator/pull/787/files#diff-bc8785e853d511edc34716d72bd63944fef9c2812acef0ff021d87f461e321e1R41) and [operator Run function](https://github.com/openshift/insights-operator/pull/787/files#diff-52732d3ec39ef3de250ba276b2f85c749aef6e8f9e34cd6066abaa5f165bdd1aL51) which contain high complexity (and more than 100 lines), I didn't find any dead-end.
Maybe it would be a good idea to revisit this later and try to refactor some parts and include some unit tests to them (currently seems impossible)

**Comment by tremes** [comment]
Thank you @ncaak. Yes you're right. There's a follow-up prepared for the https://issues.redhat.com/browse/CCXDEV-10590 and it will hopefully refactor few things.

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by deepsm007** [comment]
@tremes We are concerned about the e2e-gcp-ovn-techpreview failing job. Can we confirm if this is not an issue for merging the PR?

**Comment by tremes** [comment]
Hi @deepsm007, I realized that our current testsuite will not pass with this tech preview upgrade. So when I am looking at the last https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_insights-operator/787/pull-ci-openshift-insights-operator-master-e2e-gcp-ovn-techpreview/1669219468393320448 then I think the failures are expected. Thanks and sorry for this inconvenience. 

The `periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview` should hopefully be more indicative, because there have been already one problem (test failure - related to https://github.com/openshift/insights-operator/pull/787/commits/066865909db5e373bc911f21308675e533aad9db) that required revert of this.

**Pull request merged**
