### PR TITLE
Bug 1881044: Limit the maximum number of CSR

### PR DESCRIPTION
**Pull request by rluders**
Apply some limits to the CSR request to avoid memory issues.

### CODE REVIEW

**Comment by tremes** [comment]
lgtm

**Comment by 0sewa0** [comment]
lgtm

**Review by tisnik — APPROVED** [review]
LGTM!

**Review by natiiix — APPROVED** [review]
/lgtm

*Seems simple enough, so I didn't generate a cluster to test this locally.*

**Pull request merged**
