### PR TITLE
Fix lint, pin its version and other minor fixes

### PR DESCRIPTION
**Pull request by tremes**
## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

### CODE REVIEW

**Review by ncaak — APPROVED** [review]
/lgtm

**Comment by tremes** [comment]
This change affects only lint and generated documentation.
/override ci/prow/e2e-gcp-ovn-techpreview 
/label qe-approved

**Pull request merged**
